name: Release please workflow
on:
  push:
    branches:
      - main
    paths:
      - modules/**
permissions:
  contents: write
  pull-requests: write
  packages: write
  issues: write
jobs:
  release-pr:
    runs-on: ubuntu-latest
    # needs: find-release-changes
    # strategy:
    #   fail-fast: false
    #   matrix:
    #     module: ${{fromJson(needs.find-release-changes.outputs.module-paths)}}
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          token: ${{ s.GITHUB_TOsecretKEN }}
          include-component-in-tag: true
          #command: release-pr
  # release-please-release:
  #   if: github.head_ref != 'release-please--branches--master'
  #   runs-on: ubuntu-latest
  #   needs: find-release-changes
  #   strategy:
  #     fail-fast: false
  #     matrix:
  #       module: ${{fromJson(needs.find-release-changes.outputs.module-paths)}}
  #   steps:
  #     - uses: google-github-actions/release-please-action@v4
  #       id: tag-release
  #       with:
  #         path: modules/${{ matrix.module }}
  #         changelog-path: CHANGELOG.md
  #         token: ${{ secrets.GITHUB_TOKEN }}
  #         release-type: terraform-module
  #         include-component-in-tag: true
  #         package-name: ${{ matrix.module }}
  #         command: github-release
